version: "3.3"
services:

  jupyterhub:
    container_name: 'jupyterhub'
    build:
      context: .
      dockerfile: docker/jupyterhub.Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      JUPYTERHUB_IP: ${JUPYTERHUB_IP}
      JUPYTERHUB_PORT: ${JUPYTERHUB_PORT}
      JUPYTERHUB_CONTAINER_NAME: ${JUPYTERHUB_CONTAINER_NAME}
      JUPYTERHUB_DATA: ${JUPYTERHUB_DATA}
      ADMIN_USERS:
      OAUTH_CALLBACK_URL:
      OAUTH_CLIENT_ID:
      OAUTH_CLIENT_SECRET:
    ports:
      - 80:80
    volumes:
      - "${JUPYTERHUB_DATA}:${JUPYTERHUB_DATA}"
      - ${JUPYTERHUB_WORKSPACE}:/home
    restart: "always"
