version: "3.3"
services:

  jupyter-jupyterhub:
    container_name: 'jupyter-jupyterhub'
    build:
      context: .
      dockerfile: jupyterhub-builder/jupyterhub.Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      JUPYTERHUB_IP: ${JUPYTERHUB_IP}
      JUPYTERHUB_PORT: ${JUPYTERHUB_PORT}
      JUPYTERHUB_CONTAINER_NAME: ${JUPYTERHUB_CONTAINER_NAME}
      JUPYTERHUB_DATA: ${JUPYTERHUB_DATA}
      JUPYTERHUB_CONTAINER_DATA_DIR: ${JUPYTERHUB_CONTAINER_DATA_DIR}
      ADMIN_USERS: ${ADMIN_USERS} 
      OAUTH_CALLBACK_URL: ${OAUTH_CALLBACK_URL}
      OAUTH_CLIENT_ID: ${OAUTH_CLIENT_ID}
      OAUTH_CLIENT_SECRET: ${OAUTH_CLIENT_SECRET}
    volumes:
      - jupyterhub_data:/home/jupyterhub
      - jupyterhub_users_home:/home
    ports:
      - 8000:8000
      - 8081:8081
    restart: always
    networks: ["jupyter-connector-public"]

  # History service
  jupyter-postgres:
    image: postgres:16
    container_name: "jupyter-postgres"
    hostname: "postgres"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5439:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5      
    volumes:
      - jupyter-db:/var/lib/postgresql/data
    networks: ["jupyter-connector-public"]
 
  portainer:
    container_name: "jupyter-portainer"
    image: portainer/portainer-ce:latest
    # ports:
    #   - 9443:9443
    command: --admin-password '$$2y$$05$$ASFxrXyfALJnKE5pKh7BpulQf8829Odq7td0Ogi5NZ8pjKKMpjCwS' 
    volumes:
      - jupyter-portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks: ["jupyter-connector-public"]
 

  jupyter-swag:
    container_name: jupyter-swag
    build:
      context: "."
      dockerfile: "proxy-image-builder/Dockerfile"
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - VALIDATION=duckdns
      - SUBDOMAINS=wildcard
      - URL=${SWAG_URL}
      - EMAIL=${SWAG_EMAIL}
      - DUCKDNSTOKEN=${SWAG_DUCKDNSTOKEN}    
      - PROPAGATION=60
    volumes:
      - jupyter-swag-config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    networks: ["jupyter-connector-public"]

networks:
  jupyter-connector-public:
    name: "jupyter-connector-pjc-public"

volumes:  
  jupyterhub_data:
  jupyterhub_users_home:
  jupyter-portainer-data:
  jupyter-swag-config:
  jupyter-db: