#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# copy new actual conf
if [[ -d /defaults/nginx/proxy-confs/ ]]; then
    find /defaults/nginx/proxy-confs/ \
        -maxdepth 1 \
        -name "*.conf" \
        -type f \
        -exec cp "{}" /config/nginx/proxy-confs/ +
fi

# copy default passwd file if they don't exist
if [[ ! -f /config/nginx/.htpasswd ]]; then
    cp /defaults/nginx/.htpasswd /config/nginx/.htpasswd
fi
